### ISSUE TITLE
Can we remove useless Lists

### ISSUE THREAD

**Issue by 3la2Saber** [aliyss/syncribullet#17] opened 2024-10-01 20:53 UTC
Can we remove Completed Dropped Watched list
I think the most useful list is

SIMKL Plan To Watch Movies
Simkle Watching Series
Simkle Plan to Watch Series
Simkle Watching Anime
Simkle Plan to Watch Anime

But Other not needed in Stremio 

Again thank you for you effort

**Comment by aliyss** [comment] 2024-10-09 05:54
Duplicate of #11

**Closed by aliyss** 2024-10-09 05:54 UTC

**Comment by aliyss** [comment] 2024-10-13 21:23
Has been integrated... just reconfigure the addon
